/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postest1;

import javax.swing.JOptionPane;

/**
 *
 * @author fajarkh
 */
public class tugas2 extends javax.swing.JFrame {
int input;
int output_cf=0,output_ck=0,output_fc=0,output_fk=0,output_kc=0,output_kf=0;
    /**
     * Creates new form konversi_suhu
     */
    public tugas2() {
        initComponents();
    }
    public void parsing () {
        try {
       input=Integer.parseInt(kol_in.getText().toString());
       } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(this, "Harap Masukkan Angka saja", "Peringatan !", JOptionPane.CANCEL_OPTION); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        derajat = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        kol_in = new javax.swing.JTextField();
        in_c = new javax.swing.JRadioButton();
        in_f = new javax.swing.JRadioButton();
        in_k = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        out_f = new javax.swing.JRadioButton();
        out_c = new javax.swing.JRadioButton();
        out_k = new javax.swing.JRadioButton();
        kol_out = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        der = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        derajat.setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setBackground(new java.awt.Color(102, 255, 51));

        in_c.setText("Celcius");
        in_c.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                in_cAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        in_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_cMouseClicked(evt);
            }
        });

        in_f.setText("Fahrenheid");
        in_f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_fMouseClicked(evt);
            }
        });

        in_k.setText("Kelvin");
        in_k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                in_kMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Broadway", 1, 18)); // NOI18N
        jLabel1.setText("Input");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(in_k)
                                    .addComponent(in_f)
                                    .addComponent(in_c))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(kol_in)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kol_in, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(in_c)
                .addGap(29, 29, 29)
                .addComponent(in_f)
                .addGap(26, 26, 26)
                .addComponent(in_k)
                .addGap(23, 23, 23))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 51));

        out_f.setText("Fahrenheid");
        out_f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                out_fMouseClicked(evt);
            }
        });

        out_c.setText("Celcius");
        out_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                out_cMouseClicked(evt);
            }
        });

        out_k.setText("Kelvin");
        out_k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                out_kMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Broadway", 1, 18)); // NOI18N
        jLabel2.setText("Output");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        der.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        der.setText("       ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kol_out, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(der))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(out_c)
                            .addComponent(out_f)
                            .addComponent(out_k))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(out_c)
                .addGap(27, 27, 27)
                .addComponent(out_f)
                .addGap(14, 14, 14)
                .addComponent(out_k)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(kol_out, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(der, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setText("           PROGRAM KONVERSI SUHU");

        javax.swing.GroupLayout derajatLayout = new javax.swing.GroupLayout(derajat);
        derajat.setLayout(derajatLayout);
        derajatLayout.setHorizontalGroup(
            derajatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(derajatLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(derajatLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        derajatLayout.setVerticalGroup(
            derajatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, derajatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(derajatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(derajat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(derajat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void in_cAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_in_cAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_in_cAncestorAdded

    private void in_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_cMouseClicked
this.parsing();
        if(in_c.isSelected()==true) // if check box is checked
       {
         output_cf=(int) ((1.8 * input) + 32);
         output_ck=input + 273;
            in_f.setSelected(false);
            in_k.setSelected(false);
            out_c.setEnabled(false);
            out_f.setEnabled(true);
            out_k.setEnabled(true);
         }                     
    }//GEN-LAST:event_in_cMouseClicked

    private void out_fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_out_fMouseClicked
    this.parsing();
        if(out_f.isSelected()==true && in_c.isSelected()==true){ kol_out.setText(""+output_cf); 
            out_c.setSelected(false);
            out_k.setSelected(false);
            der.setText("F");}
        else if(out_f.isSelected()==true && in_k.isSelected()==true){ kol_out.setText(""+output_kf); 
            out_k.setSelected(false);
            out_c.setSelected(false);
            der.setText("F");}
        else { kol_out.setText(""); der.setText("");}
    }//GEN-LAST:event_out_fMouseClicked

    private void in_fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_fMouseClicked
this.parsing();
        if(in_f.isSelected()==true) // if check box is checked
       {    output_fc=(int) (0.55 * (input - 32));
            output_fk=(int) (0.55 * (input - 32) + 273);
            in_c.setSelected(false);
            in_k.setSelected(false);
            out_f.setEnabled(false);
            out_c.setEnabled(true);
            out_k.setEnabled(true);
         }
    }//GEN-LAST:event_in_fMouseClicked

    private void in_kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_in_kMouseClicked
this.parsing();
        if(in_k.isSelected()==true) // if check box is checked
       {    output_kc=input-273;
            output_kf=(int) (1.8 * (input-273)+32);
            in_c.setSelected(false);
            in_f.setSelected(false);
            out_k.setEnabled(false);
            out_f.setEnabled(true);
            out_c.setEnabled(true);
         }
    }//GEN-LAST:event_in_kMouseClicked

    private void out_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_out_cMouseClicked
this.parsing();
        if(out_c.isSelected()==true && in_f.isSelected()==true){ kol_out.setText(""+output_fc); 
            out_k.setSelected(false);
            out_f.setSelected(false); 
        der.setText("C");}
       else if(out_c.isSelected()==true && in_k.isSelected()==true){ kol_out.setText(""+output_kc); 
                out_k.setSelected(false);
                out_f.setSelected(false);
       der.setText("C");}
        else { kol_out.setText(""); der.setText("");}
    }//GEN-LAST:event_out_cMouseClicked

    private void out_kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_out_kMouseClicked
this.parsing();
        if(out_k.isSelected()==true && in_c.isSelected()==true){ kol_out.setText(""+output_ck); 
            out_f.setSelected(false);
            out_c.setSelected(false);
            der.setText("K");}
        else if(out_k.isSelected()==true && in_f.isSelected()==true){ kol_out.setText(""+output_fk); 
            out_f.setSelected(false);
            out_c.setSelected(false);
            der.setText("K");}
        else { kol_out.setText(""); der.setText("");}
    }//GEN-LAST:event_out_kMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel der;
    private javax.swing.JPanel derajat;
    private javax.swing.JRadioButton in_c;
    private javax.swing.JRadioButton in_f;
    private javax.swing.JRadioButton in_k;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField kol_in;
    private javax.swing.JTextField kol_out;
    private javax.swing.JRadioButton out_c;
    private javax.swing.JRadioButton out_f;
    private javax.swing.JRadioButton out_k;
    // End of variables declaration//GEN-END:variables
}
